grocery.coords <- readRDS("grocery.coords.rds")
zillow_home_value <- readRDS("zillow_home_value.rds")
zillow_home_value_monthly_diff <- readRDS("zillow_home_value_monthly_diff.rds")
zillow_home_value_monthly_diff_wide <- readRDS("zillow_home_value_monthly_diff_wide.rds")
zillow_value_vs_growth <- readRDS("zillow_value_vs_growth.rds")
county_metric <- readRDS("county_metrics.rds")
walkscore <- readRDS("nh_walkscoredata.rds")
nh_basic_map <- readRDS("nh_basic_map.rds")  
nh_base <- readRDS("nh_base_ggmap.rds") 
zips_sf <- readRDS("zips_sf.rds")
food.desert_sf <- readRDS("food_desert_shapes.rds") %>% st_set_crs(4269)
